export const CURRENCY_CONVERT_REQUEST = 'CURRENCY_CONVERT_REQUEST';
export const CURRENCY_CONVERT_RESPONSE = 'CURRENCY_CONVERT_RESPONSE';
export const CURRENCY_CONVERT_FAILURE = 'CURRENCY_CONVERT_FAILURE';